app: siesta
service: siesta-api

plugins:
  - serverless-python-requirements

provider:
  name: aws
  profile: kxptech
  runtime: python3.9
  stage: dev
  region: sa-east-1
  httpApi:
    cors: true

functions:
  siestaTime:
    handler: handler.siesta_time
    events:
      - alexaSkill: amzn1.ask.skill.234fce4d-8f7a-4d07-ba20-98d5279b74d3
